version: '2'
services:
    web1:
        image: strm/helloworld-http
        container_name: web1
        ports:
                - "8081:80"
    web2:
        image: strm/helloworld-http
        container_name: web2
        ports:
                - "8082:80"
